from marshmallow import Schema, fields

class Pollutions(Schema):
    pollution_date = fields.Date()
    no2_mean = fields.Float()
    no2_max_value = fields.Int()
    no2_max_hour = fields.Int()
    no2_aqi = fields.Int()
    o3_mean = fields.Float()
    o3_max_value = fields.Int()
    o3_max_hour = fields.Int()
    o3_aqi = fields.Int()
    so2_mean = fields.Float()
    so2_max_value = fields.Int() 
    so2_max_hour = fields.Int()
    so2_aqi = fields.Int()
    CO_mean = fields.Float()
    CO_max_value = fields.Int() 
    CO_max_hour = fields.Int()
    CO_aqi = fields.Int()
